Version: 1.2

Logging:
    Verbose: True

General:
    SqrtsNN: 5360.0
    Nucleus1:
        A:    208
        Z:    82
        mode: 0
    Nucleus2:
        A:    208
        Z:    82
        mode: 0
    GlauberAcceptance: Gaussian
    Events: 500
    Model: 1
    Impact:
        Range: [0, 40]
        Sampling: Quadratic
    PDFs:
      PDFSet: CT18NNLO
      ForcePositive: 1
    K-Factor: 2.25

Thickness:
    TMax:   15.0
    TMin:   0.0
    NT:     151
    fluct_mode: LogNormal
    thick_fluct: 0.563

Grid:
    NX:        251
    NY:        251
    NETA:      251
    X_RANGE:   [-15,15]
    Y_RANGE:   [-15,15]
    ETA_RANGE: [-15,15]
    BG: 0.156
    HOTSPOTS_WIDTH: 0.116
    HOTSPOTS_NUM: 3

Model_Parameters:
    Set:   1
    XScaling: 0.01
    P_reg: 0.00001

Output:
    path_to_output: /work/temp/zhujie/McDipper_ini
    run_name: PbPb_5360GeV_IPSat_Set1_batch110
    Format: ["EMoments","Charges"]
