Version: 1.0

Logging:
    Verbose: True

General:
    SqrtsNN: 5020.0
    Nucleus1:
        A:    16
        Z:    8
        mode: 3
        InputFile: filename_oxygen
        IsospinSpecified: True
        Configurations: 20000
    Nucleus2:
        A:    16
        Z:    8
        mode: 3 
        InputFile: filename_oxygen
        IsospinSpecified: True
        Configurations: 20000
    GlauberAcceptance: Gaussian
    Events: 10
    Model: 1
    Impact:
        Range: [0, 40]
        Sampling: Quadratic
    Seed: 1129279364
    PDFs:
      PDFSet: CT18NNLO
      ForcePositive: 1
    K-Factor: 1.

Grid:
    NX:        241
    NY:        241
    NETA:      101
    X_RANGE:   [-12,12]
    Y_RANGE:   [-12,12]
    ETA_RANGE: [-10,10]
    BG: 0.156

Model_Parameters:
    Set:   1
    XScaling: 0.01
    P_reg: 0.1 

Output:
    path_to_output: out/
    run_name: Test_Run
    Format: ["EMoments","NMoments"]
    PrintAvg: False
    BoostInvariant: False